# Generated by Django 5.1.2 on 2024-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('R&B', 'R&B'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Country', 'Country'), ('Dance Music', 'Dance Music'), ('Hip Hop', 'Hip Hop'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='album',
            name='img_url',
            field=models.URLField(),
        ),
    ]
